export default {
  mainnet: {
    nodeUrl: 'https://nodes.wavesnodes.com/',
    managerPublicKey: '2Cbd8ozG7A1RyRNC3nNnZgHu7Ru4K3JCfpyPkhqr9zxq',
    assetsStorePublicKey: 'Ajaez2Qx6UNQu7rT1BceE2hNDrQd52fLHsoq7Js5q3by',
    userPoolsPublicKey: '52HVeUFDYgRVXrPNfdX4WinZBFdizmuf1vqmbd8ExAZS',
    factoryPublicKey: 'HBWgh7DKPyzCnEXKJAJ5dKQ3jmPtMhGD78tt6jRdkV61',
    votingVerifiedPublicKey: '7wRNg48gMG7eZWCzb7RedQqoccX7Tx6Foptzk7Nxkv7H',
    tokensWithLabelsUrl: 'https://waves.exchange/api/v1/assets?label__in[]=DEFI&label__in[]=GATEWAY&label__in[]=STABLECOIN&label__in[]=WA_VERIFIED&label__in[]=COMMUNITY_VERIFIED',
    chainId: 87,
    wxAssetId: 'Atqv59EYzjFGuitKVnMRk6H8FukjoV3ktPorbEys25on',
    usdnAssetId: 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p',
  },
  testnet: {
    nodeUrl: 'https://nodes-testnet.wavesnodes.com/',
    managerPublicKey: 'EsqRXDXnACFAdXz6EPhF1SbKyeV7MVuoyDqmXsMz7ySv',
    assetsStorePublicKey: 'EtZZHS4uqNXY5WPneZ8jY2aA95peXwthJVLzAMxMp379',
    userPoolsPublicKey: 'Ap7CkWd6fzBU34kGo4GJJzC5q4qWXuLVunzE25PchdGS',
    factoryPublicKey: '2JEaBjtjvMoNGKZmL9QxYefa1VkMJM3vMW8rNvTs9R2H',
    votingVerifiedPublicKey: 'C2aAS9D6FqfbrkCuCQCtPWAiopjyagvitFLjRuLcRPYt',
    tokensWithLabelsUrl: 'https://testnet.waves.exchange/api/v1/assets?label__in[]=DEFI&label__in[]=GATEWAY&label__in[]=STABLECOIN&label__in[]=WA_VERIFIED&label__in[]=COMMUNITY_VERIFIED',
    chainId: 84,
    wxAssetId: 'EMAMLxDnv3xiz8RXg8Btj33jcEw3wLczL3JKYYmuubpc',
    usdnAssetId: '25FEqEjRkqK6yCkiT7Lz6SAYz7gUFCtxfCChnrVFD5AT',
  },
};
