export default {
  mainnet: {
    nodeUrl: 'https://nodes.wavesnodes.com/',
    managerPublicKey: '2Cbd8ozG7A1RyRNC3nNnZgHu7Ru4K3JCfpyPkhqr9zxq',
    factoryPublicKey: 'HBWgh7DKPyzCnEXKJAJ5dKQ3jmPtMhGD78tt6jRdkV61',
    boostingPublicKey: '6PdA345SW1zresPEKuWiLPsh9Ku14mFDW6cZtpCQrp3E',
    gwxRewardPublicKey: 'G349Uq3FTox7dRNLeAfAQeoACvwZ9iEnVSaHcEYn6j8J',
    referralPublicKey: '33fpjdpM9FMu87RZKePniPardKqQXM96sm7VhAk3JEVQ',
    marketingPublicKey: '3EfudNNQNACtTotZKwkRu97fZW5fFjUPwuP1gd3oBHJs',
    backendSignerPublicKey: '7xZThMgqjfP71zMErfRXkTrthGkN6dYdmJB4ci8HYEoj',
    chainId: 87,
    wxAssetId: 'Atqv59EYzjFGuitKVnMRk6H8FukjoV3ktPorbEys25on',
  },
  testnet: {
    nodeUrl: 'https://nodes-testnet.wavesnodes.com/',
    managerPublicKey: 'EsqRXDXnACFAdXz6EPhF1SbKyeV7MVuoyDqmXsMz7ySv',
    factoryPublicKey: '2JEaBjtjvMoNGKZmL9QxYefa1VkMJM3vMW8rNvTs9R2H',
    boostingPublicKey: '9W33iCCNfmFxUbiC6XZcH5x7f6xfwC7Jb3BoExT5q2PV',
    gwxRewardPublicKey: '4Uv4fNGxmwhwHRipWuYvZe87BazB9H19nVEac9pguorM',
    referralPublicKey: 'AEV7LzxNAcdrjC2NC4182iTxuyTyqfCLzqJ14TXnVSCm',
    marketingPublicKey: 'rtorwpe32pLWq5ZZJobchM1AJJcZ31hipQ5SW7i6xff',
    backendSignerPublicKey: 'CC35KFHBKs3LqekXLrVuJQbmqkswgHUhBQUsf5SJwiZx',
    chainId: 84,
    wxAssetId: 'EMAMLxDnv3xiz8RXg8Btj33jcEw3wLczL3JKYYmuubpc',
  },
};
