export default {
  mainnet: {
    nodeUrl: 'https://nodes.wavesnodes.com/',
    managerPublicKey: '2Cbd8ozG7A1RyRNC3nNnZgHu7Ru4K3JCfpyPkhqr9zxq',
    assetsStorePublicKey: 'Ajaez2Qx6UNQu7rT1BceE2hNDrQd52fLHsoq7Js5q3by',
    userPoolsPublicKey: '52HVeUFDYgRVXrPNfdX4WinZBFdizmuf1vqmbd8ExAZS',
    factoryPublicKey: 'HBWgh7DKPyzCnEXKJAJ5dKQ3jmPtMhGD78tt6jRdkV61',
    votingEmissionPublicKey: '7CCBtvKD4K6UAqDwpQKssA3WsvR2sdh1rq7CEZ5Gp5aL',
    votingEmissionCandidatePublicKey: 'DQtGXvog3Y6B9bxto8pajLFKjsTX8tBjkDi6RRhtP8X5',
    stakingPublicKey: 'EAtbDa63mS5omrvW7Pfr7DKWEVLuReJtu72vfiBLRXsx',
    boostingPublicKey: '6PdA345SW1zresPEKuWiLPsh9Ku14mFDW6cZtpCQrp3E',
    emissionPublicKey: 'FoGdD9qz4AFW3pdmp1QCA5vvo9wn3fTbv4JnYrWZe3BB',
    migratorPublicKey: '4nmiwe64cTYYr63v3Yj8tYELUtdxujuG7sqHkB1DXykt',
    chainId: 87,
    wxAssetId: 'Atqv59EYzjFGuitKVnMRk6H8FukjoV3ktPorbEys25on',
    usdnAssetId: 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p',
  },
  testnet: {
    nodeUrl: 'https://nodes-testnet.wavesnodes.com/',
    managerPublicKey: 'EsqRXDXnACFAdXz6EPhF1SbKyeV7MVuoyDqmXsMz7ySv',
    assetsStorePublicKey: 'EtZZHS4uqNXY5WPneZ8jY2aA95peXwthJVLzAMxMp379',
    userPoolsPublicKey: 'Ap7CkWd6fzBU34kGo4GJJzC5q4qWXuLVunzE25PchdGS',
    factoryPublicKey: '2JEaBjtjvMoNGKZmL9QxYefa1VkMJM3vMW8rNvTs9R2H',
    votingEmissionPublicKey: 'D46gQxzmdzdCTYRg6dMcwFoUrc6ZmxF6GKd5ZoTkvzp1',
    votingEmissionCandidatePublicKey: '7iXEgsFNsnbLZ3ca4tmz8jffnyxMu9keuBV6CuQPJLuA',
    stakingPublicKey: 'D28XoueZWsMfm8Y5pa6C5ZFuYoWgre2Wm8tzJANJgMnq',
    boostingPublicKey: '9W33iCCNfmFxUbiC6XZcH5x7f6xfwC7Jb3BoExT5q2PV',
    emissionPublicKey: 'H19CeJVbUnfsK8EYs8K6fHxwBH7pLyxw8WCDFu7D4rGQ',
    migratorPublicKey: '3dnJqgo3xCftAjPTv2M8rcYCponprYL3RJNcenTn3DKh',
    chainId: 84,
    wxAssetId: 'EMAMLxDnv3xiz8RXg8Btj33jcEw3wLczL3JKYYmuubpc',
    usdnAssetId: '25FEqEjRkqK6yCkiT7Lz6SAYz7gUFCtxfCChnrVFD5AT',
  },
};
