name: CI
on: push

jobs:
  compile:
    env:
      TESTNETNODE: ${{ secrets.TESTNETNODE }}
      MAINNETNODE: ${{ secrets.MAINNETNODE }}
    runs-on: ubuntu-20.04
    container:
      image: golang:1.18
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Compile .ride files
        run: |
          cd compiler
          go run main.go

  deploy_testnet:
    env:
      MODE: deployTestnet
      TESTNETNODE: ${{ secrets.TESTNETNODE }}
      MAINNETNODE: ${{ secrets.MAINNETNODE }}
    if: github.ref_name == 'dev'
    runs-on: ubuntu-20.04
    container:
      image: golang:1.18
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Deploy changed contracts to testnet
        run: |
          cd deployer
          go run main.go

  compare_mainnet:
    env:
      MODE: compareMainnet
      TESTNETNODE: ${{ secrets.TESTNETNODE }}
      MAINNETNODE: ${{ secrets.MAINNETNODE }}
    if: |
      github.ref_name == 'dev' ||
      github.ref_name == 'main'
    runs-on: ubuntu-20.04
    container:
      image: golang:1.18
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Compare contracts with mainnet and print diff
        run: |
          cd deployer
          go run main.go

  test:
    runs-on: ubuntu-20.04
    container:
      image: node:18.1
    services:
      waves-private-node:
        image: wavesplatform/waves-private-node
        ports:
          - 6869:6869
    env:
      API_NODE_URL: http://waves-private-node:6869
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run tests on private node
        run: |
          npm i
          npm run ci-test

  lint_go:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.18
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check .go code gofmt-formatted
        run: |
          gofmt -l .

  lint_js:
    runs-on: ubuntu-20.04
    container:
      image: node:18.1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check .js and .mjs code eslint-formatted
        run: |
          npm i
          npm run lint
