name: CI
on: push

jobs:
  compile:
    env:
      TESTNETNODE: ${{ secrets.TESTNETNODE }}
      MAINNETNODE: ${{ secrets.MAINNETNODE }}
    runs-on: self-hosted
    container:
      image: golang:1.18
      options: --user root
    steps:
      - name: Clean step
        uses: mickem/clean-after-action@v1
        if: always()
        with:
          keepGit: true
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Compile .ride files
        run: |
          cd compiler
          go run main.go
      - name: Clean repo
        uses: AutoModality/action-clean@v1
        if: always()

  deploy_testnet:
    env:
      BRANCH: ${{ github.ref_name }}
      NETWORK: testnet
      NODE: ${{ secrets.TESTNETNODE }}
      MONGOURI: ${{ secrets.TESTNETMONGOURI }}
      MONGODATABASENAME: ${{ secrets.TESTNETMONGODATABASENAME }}
      MONGOCOLLECTIONCONTRACTS: ${{ secrets.TESTNETMONGOCOLLECTIONCONTRACTS }}
      MONGOCOLLECTIONBRANCHES: ${{ secrets.TESTNETMONGOCOLLECTIONBRANCHES }}
      COMPARELPSCRIPTADDRESS: 3N6wAa7PMFZJu4Zrmp3avXmMnRTrRpMM9Lh # WX/USDN pool
      COMPARELPSTABLESCRIPTADDRESS: 3NAefciWv6f9fWvEXdGgpHfanJFG8HqfjuT # USDT/USDN pool
      COMPARELPSTABLEADDONSCRIPTADDRESS: 3N8bnD2caKnxdcTqvrJUEkDe3XebgfwWjSV # USDT/USDN pool addon
      FEESEED: ${{ secrets.TESTNETFEESEED }}
    runs-on: self-hosted
    permissions:
      contents: write
    container:
      image: golang:1.19
      options: --user root
    steps:
      - name: Clean step
        uses: mickem/clean-after-action@v1
        if: always()
        with:
          keepGit: true
      - name: Set Git config
        run: |
          export GIT_CEILING_DIRECTORIES=/__w
          git config --global --add safe.directory /__w/waves-exchange/contracts
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Deploy changed contracts
        run: |
          cd deployer
          go run main.go
      - name: Update docs
        run: |
          git add .
          git commit -m update docs
          git push
      - name: Clean repo
        uses: AutoModality/action-clean@v1
        if: always()

  deploy_mainnet:
    env:
      BRANCH: ${{ github.ref_name }}
      NETWORK: mainnet
      NODE: ${{ secrets.MAINNETNODE }}
      MONGOURI: ${{ secrets.MAINNETMONGOURI }}
      MONGODATABASENAME: ${{ secrets.MAINNETMONGODATABASENAME }}
      MONGOCOLLECTIONCONTRACTS: ${{ secrets.MAINNETMONGOCOLLECTIONCONTRACTS }}
      MONGOCOLLECTIONBRANCHES: ${{ secrets.MAINNETMONGOCOLLECTIONBRANCHES }}
      COMPARELPSCRIPTADDRESS: 3PCENpEKe8atwELZ7oCSmcdEfcRuKTrUx99 # WX/USDN pool
      COMPARELPSTABLESCRIPTADDRESS: 3P8KMyAJCPWNcyedqrmymxaeWonvmkhGauz # USDT/USDN pool
      COMPARELPSTABLEADDONSCRIPTADDRESS: 3P36szQtxxpSaefdqaFjbM9Ush8ieCjVZVw # USDT/USDN pool addon
      FEESEED: ${{ secrets.MAINNETFEESEED }}
    if: github.ref_name == 'main'
    runs-on: self-hosted
    container:
      image: golang:1.19
      options: --user root
    steps:
      - name: Clean repo
        uses: AutoModality/action-clean@v1
        if: always()
      - name: Clean step
        uses: mickem/clean-after-action@v1
        if: always()
        with:
          keepGit: true
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Compare contracts and print diff. Deploy changed lp.ride
        run: |
          cd deployer
          go run main.go
      - name: Update docs
        run: |
          git add .
          git commit -m update docs
          git push
      - name: Save txs to sign in artifact folder
        uses: actions/upload-artifact@v3
        with:
          name: txs
          path: .github/artifacts/txs

  lint_go:
    runs-on: self-hosted
    container:
      image: golang:1.18
      options: --user root
    steps:
      - name: Clean step
        uses: mickem/clean-after-action@v1
        if: always()
        with:
          keepGit: true
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check .go code gofmt-formatted
        run: |
          gofmt -l .
      - name: Clean repo
        uses: AutoModality/action-clean@v1
        if: always()

  lint_js:
    runs-on: self-hosted
    container:
      image: node:18.1
      options: --user root
    steps:
      - name: Clean step
        uses: mickem/clean-after-action@v1
        if: always()
        with:
          keepGit: true
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check .js and .mjs code eslint-formatted
        run: |
          cd test
          npm i
          npm run lint
      - name: Clean repo
        uses: AutoModality/action-clean@v1
        if: always()

  test:
    runs-on: self-hosted
    container:
      image: node:18.1
      options: --user root
    services:
      waves-private-node:
        image: wavesplatform/waves-private-node
    env:
      API_NODE_URL: http://waves-private-node:6869
    steps:
      - name: Clean step
        uses: mickem/clean-after-action@v1
        if: always()
        with:
          keepGit: true
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run tests on private node
        run: |
          cd test
          npm i
          npm run ci-test
      - name: Clean repo
        uses: AutoModality/action-clean@v1
        if: always()
