name: Test
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branches"
        required: true
        default: 'main'
        type: choice
        options:
          - test-workflow

jobs:
  test:
    runs-on: self-hosted
    container:
      image: node:18.1
    services:
      waves-private-node:
        image: wavesplatform/waves-private-node
    env:
      API_NODE_URL: http://waves-private-node:6869
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run tests on private node
        run: |
          cd test
          npm i
          npm run ci-test